name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    services:
      redis:
        image: "redis:6.2.3"
        ports:
          - 6379:6379
      cassandra:
        image: "cassandra:3.11.10"
        env:
          JVM_OPTS: "-Dcassandra.skip_wait_for_gossip_to_settle=0"
          HEAP_NEWSIZE: "32m"
          MAX_HEAP_SIZE: "256m"
          CASSANDRA_START_RPC: "true"
        ports:
          - 9042:9042

    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        java: [11]
        platform: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache maven packages
        uses: actions/cache@v2
        env:
          cache-name: cache-sbt
        with:
          path: ~/.m2 ~/.coursier ~/.cache/coursier ~/.ivy2 ~/.sbt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Run tests
        run: sbt test